led:
  ws2812b:
    driver: spi
    device: /dev/spidev4.0
    # WS2812B DIN is connected to SPI4 MOSI.
    spi_bus: 4
    spi_device: 0
    spi_speed_hz: 2400000
    bit0_pattern: "100"
    bit1_pattern: "110"
    color_order: GRB
    # Set this to the total number of WS2812B LEDs in the ring.
    count: 90
    default_brightness_pct: 80  # 默认亮度
    max_brightness_pct: 100
    state_file: /home/elf/projects/datas/csv/led_state.csv
    sensor_csv: /home/elf/projects/datas/csv/sensor_realtime.csv
